### ISSUE TITLE
Bug found in webmail v8 Invalid credentials

### ISSUE THREAD

**Issue by lota** [afterlogic/aurora-module-ldap-change-password-plugin#1]
In webmail v8, change password does not works, you get the error
`LDAP: error #49: Invalid credentials` (with correct credentials)
this due an attempt to bind (to check current password) with password
`username:password ` instead `password`

I use a "rough" patch in system/Utils/Ldap.php ~105

```
// RHX patch
if (strpos($a, ':') !== false) {
    $sBindPassword_array= explode (':', $sBindPassword , 2 );
    $sBindPassword=$sBindPassword_array[1];
}
// /RHX patch
```

just before

`\Aurora\System\Api::Log('LDAP: bind = "'.$sBindDb.'" / "'.$sBindPassword.'"');`

to use correct password if it contains ":" char

this is not a good solution, please correct the bug

HTH
Alessandro

**Comment by afterlogic-support** [comment]
Thank you, developers have implemented an update which will become available in then next release.
