### ISSUE TITLE
LDAPS support

### ISSUE THREAD

**Issue by rowra44** [afterlogic/aurora-module-ldap-change-password-plugin#2]
Please add support for LDAPS both via SSL/TLS and STARTTLS

**Comment by afterlogic-support** [comment]
Thank you for the suggestion. Please feel free to post a feature request at:
https://afterlogic.uservoice.com/forums/932335-webmail-pro
We use that resource when developing products' roadmap, so if the feature gets a good number of votes, there's a better chance of it being implemented.
